services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=bgu
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3360:3306
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=pass
    ports:
      - 6379:6379

volumes:
  mysql-data: