spring:
  servlet:
    multipart:
      max-file-size: 3MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/bgu
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: redis
      port: 6379
      password: ${RESIS_PASSWORD}

secret:
  key: ${JWT_SECRET:vR4cTn8gWpL3dQ9fGz6S2hDkZxJm5uXqV0yP8sNw1bFj7YtAqE3rPzLwWbJkKr5iShzO2vTg9Q4pFz0KmXtN6V7eYd}
  cors: ${CORS:http://localhost:5173}
  captcha-secret: ${CAPTCHA_SECRET:Tn8gWLocalConEnyMerFtoryBanpL3dQ9fGz6S2hDkZxJm5uXqV0yP8sNw1b}
  captcha-expiry: 300
  api-base-url: ${API_BASE_URL:http://localhost:8080}
  ticket-code: ${TICKET_CODE:kk}
  bgu-mail-domain: ${BGU_MAIL_DOMAIN:bgu.ac.in}

email-id:
  accounts:
    - email: ${EMAIL1}
      password: ${PASSWORD1}
    - email: ${EMAIL2}
      password: ${PASSWORD2}