services:
  mysql:
    container_name: bgu-mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=bgu
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3360:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      private-net:

  redis:
    container_name: bgu-redis
    image: redis:latest
    environment:
      - REDIS_PASSWORD=pass
    ports:
      - 6379:6379
    networks:
      - private-net
  api:
    container_name: bgu-api
    image: srinibashsai/bgu-api:1.0
    ports:
      - 8080:8080
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      private-net:
    depends_on:
      - mysql
      - redis
    restart: on-failure


networks:
  private-net: